// <auto-generated />
namespace dot_net_mid_assignment_Tamim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedForeignkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedForeignkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "202303281625451_AddedForeignkeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
